CAR_MOTION_DATA_COUNT = 22
PARTICIPANT_DATA_COUNT = 22
LAP_DATA_COUNT = 22

CAR_SETUP_DATA_COUNT = 22
CAR_TELEMETRY_DATA_COUNT = 22
CAR_STATUS_DATA_COUNT = 22

FINAL_CLASSIFICATION_DATA_COUNT = 22
LOBBY_INFO_DATA_COUNT = 22

MARSHAL_ZONE_COUNT = 21

WEATHER_SAMPLES_COUNT = 56

NAME_OF_PARTICIPANT_COUNT = 48
