from .packet import (
    PacketCarDamageData,
    PacketCarSetupData,
    PacketCarStatusData,
    PacketCarTelemetryData,
    PacketEventData,
    PacketFinalClassificationData,
    PacketLapData,
    PacketLapPositionsData,
    PacketLobbyInfoData,
    PacketMotionData,
    PacketMotionExData,
    PacketParticipantsData,
    PacketSessionData,
    PacketSessionHistoryData,
    PacketTimeTrialData,
    PacketTyreSetsData,
)

PACKET_PARSERS = {
    0: PacketMotionData.parse,
    1: PacketSessionData.parse,
    2: PacketLapData.parse,
    3: PacketEventData.parse,
    4: PacketParticipantsData.parse,
    5: PacketCarSetupData.parse,
    6: PacketCarTelemetryData.parse,
    7: PacketCarStatusData.parse,
    8: PacketFinalClassificationData.parse,
    9: PacketLobbyInfoData.parse,
    10: PacketCarDamageData.parse,
    11: PacketSessionHistoryData.parse,
    12: PacketTyreSetsData.parse,
    13: PacketMotionExData.parse,
    14: PacketTimeTrialData.parse,
    15: PacketLapPositionsData.parse,
}
